from yacs.config import CfgNode as CN

PLANE_HEAD = CN()

PLANE_HEAD.N_DYN_PLANES = 20
PLANE_HEAD.N_STATIC_POS_PLANES  = 10
PLANE_HEAD.N_STATIC_NEG_PLANES  = 10
PLANE_HEAD.DIM_LINE_POOL = 3
PLANE_HEAD.N_PTS0 = 16
PLANE_HEAD.N_PTS1 = 4
PLANE_HEAD.DIM_FC = 1024
PLANE_HEAD.TOPK_EDGES = 30
PLANE_HEAD.EDGE_VALID_SCORE_THRESHOLD = 0.5
PLANE_HEAD.PLANE_SCORE_THRESHOLD = 0.8

PLANE_HEAD.TOPK_OUTPUT_PLANES = 50

PLANE_HEAD.LAYERS = 2
PLANE_HEAD.JUNCTION_LAYERS = 2
PLANE_HEAD.USE_QUADTREE = False
PLANE_HEAD.LOSS_WEIGHTS = None
PLANE_HEAD.CENTROID_LOSS_WEIGHTS = None
PLANE_HEAD.STRATEGY = "line_sampling"

PLANE_HEAD.NMS_IOU_THRESHOLD = -1.0

PLANE_HEAD.HGT_TOPK_LINE_CONNECTIONS = 5
PLANE_HEAD.HGT_TOPK_JUNCTION_CONNECTIONS = 5
PLANE_HEAD.HGT_POLYGON_LINE_SCORE_THRESHOLD = 0.05
PLANE_HEAD.HGT_DIM_HIDDEN = 128
PLANE_HEAD.HGT_DIM_IN = 128
PLANE_HEAD.HGT_CLASSIFIER_CONNECT_PLANES = False
PLANE_HEAD.HGT_ANCHORS_PER_SIDE = 5
PLANE_HEAD.HGT_CLASSIFIER_MINIMUM_AVERAGE_WEIGHT_ITERATIONS = 5
PLANE_HEAD.HGT_LINK_PREDICTION_POS_WEIGHT = 10.0
PLANE_HEAD.HGT_NUM_LAYERS = 3
PLANE_HEAD.HGT_NUM_ATTN_HEADS = 8
