from yacs.config import CfgNode as CN


SOLVER = CN()
SOLVER.IMS_PER_BATCH = 6
SOLVER.MAX_EPOCH = 30
SOLVER.OPTIMIZER = "ADAM"
SOLVER.BASE_LR = 0.01
SOLVER.BACKBONE_LR_FACTOR=1.0
SOLVER.BIAS_LR_FACTOR = 1

SOLVER.WEIGHT_DECAY = 0.0002
SOLVER.WEIGHT_DECAY_BIAS = 0

SOLVER.LR_SCHEDULER = 'MULTISTEP'
SOLVER.CHECKPOINT_PERIOD = 1
SOLVER.VAL_PERIOD = 1
SOLVER.NUM_GPUS = 1

# ======WARMPUP==========
SOLVER.WARMUP_EPOCHS = 0
SOLVER.WARMUP_LR_MODIFIER = 0.1

# ====== SGD ========
SOLVER.MOMENTUM = 0.9

# ====== ADAM ========
SOLVER.AMSGRAD = False

# ======Multistep LR ========
SOLVER.STEPS = (25,)
SOLVER.GAMMA = 0.1

# =======Cosine Annealing =======
SOLVER.FIRST_RESTART = 2
SOLVER.ETA_MIN_MULTIPLIER = 0.01
